Remove package resolve for tests of examples
This was causing the error
```
ERROR: Unsatisfiable requirements detected for package Pkg [44cfe95a]:
 Pkg [44cfe95a] log:
 ├─possible versions are: 1.8.0 or uninstalled
 └─restricted to versions 1.6.0 by an explicit requirement — no versions left

when using the development version of julia (aka v1.8.0-DEV.90).  I
don't think we should need the resolve as we are generating a new
manifest for each example.